name: Tourism Management System CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: login in to Amazon ECR 
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin 323890959625.dkr.ecr.us-east-1.amazonaws.com/tms
      - name:  image pull from docker hub
        run: |
          docker pull vaibhavpatil45/tms-nginx:1.0
      - name: Tag image for ECR
        run: |
          docker tag vaibhavpatil45/tms-nginx:1.0 323890959625.dkr.ecr.us-east-1.amazonaws.com/tms:latest
      - name: Push image to ECR
        run: |
          docker push 323890959625.dkr.ecr.us-east-1.amazonaws.com/tms:latest
  
  Deploy-to-EKS:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name ${{ secrets.EKS_CLUSTER_NAME }}
      - name: test kubectl 
        run: |
          kubectl get nodes
      -  name: apply k8s manifests
        run: |
          kubectl apply -f k8s-manifests/  --validate=false

